on:
  push:
    branches: [ '**' ]

jobs:
  linux:
    runs-on: ubuntu-22.04
    name: Linux tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: x64
      - run: python3 tests.py --ci

  mac:
    runs-on: macos-12
    name: macOS tests
    env:
      GCC: gcc-11
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: x64
      - run: python3 tests.py --ci

  windows:
    runs-on: windows-2022
    name: Windows tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: x64
      - run: python3 tests.py --ci
