on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  linux:
    runs-on: ubuntu-22.04
    name: Linux tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          architecture: x64
      - run: python tests.py
